CREATE TABLE Match (
	id	SERIAL PRIMARY KEY,
	country_id	INTEGER,
	league_id	INTEGER,
	season	TEXT,
	stage	INTEGER,
	date	TEXT,
	match_api_id	INTEGER UNIQUE,
	home_team_api_id	INTEGER,
	away_team_api_id	INTEGER,
	home_team_goal	INTEGER,
	away_team_goal	INTEGER,
	home_player_X1	INTEGER,
	home_player_X2	INTEGER,
	home_player_X3	INTEGER,
	home_player_X4	INTEGER,
	home_player_X5	INTEGER,
	home_player_X6	INTEGER,
	home_player_X7	INTEGER,
	home_player_X8	INTEGER,
	home_player_X9	INTEGER,
	home_player_X10	INTEGER,
	home_player_X11	INTEGER,
	away_player_X1	INTEGER,
	away_player_X2	INTEGER,
	away_player_X3	INTEGER,
	away_player_X4	INTEGER,
	away_player_X5	INTEGER,
	away_player_X6	INTEGER,
	away_player_X7	INTEGER,
	away_player_X8	INTEGER,
	away_player_X9	INTEGER,
	away_player_X10	INTEGER,
	away_player_X11	INTEGER,
	home_player_Y1	INTEGER,
	home_player_Y2	INTEGER,
	home_player_Y3	INTEGER,
	home_player_Y4	INTEGER,
	home_player_Y5	INTEGER,
	home_player_Y6	INTEGER,
	home_player_Y7	INTEGER,
	home_player_Y8	INTEGER,
	home_player_Y9	INTEGER,
	home_player_Y10	INTEGER,
	home_player_Y11	INTEGER,
	away_player_Y1	INTEGER,
	away_player_Y2	INTEGER,
	away_player_Y3	INTEGER,
	away_player_Y4	INTEGER,
	away_player_Y5	INTEGER,
	away_player_Y6	INTEGER,
	away_player_Y7	INTEGER,
	away_player_Y8	INTEGER,
	away_player_Y9	INTEGER,
	away_player_Y10	INTEGER,
	away_player_Y11	INTEGER,
	home_player_1	INTEGER,
	home_player_2	INTEGER,
	home_player_3	INTEGER,
	home_player_4	INTEGER,
	home_player_5	INTEGER,
	home_player_6	INTEGER,
	home_player_7	INTEGER,
	home_player_8	INTEGER,
	home_player_9	INTEGER,
	home_player_10	INTEGER,
	home_player_11	INTEGER,
	away_player_1	INTEGER,
	away_player_2	INTEGER,
	away_player_3	INTEGER,
	away_player_4	INTEGER,
	away_player_5	INTEGER,
	away_player_6	INTEGER,
	away_player_7	INTEGER,
	away_player_8	INTEGER,
	away_player_9	INTEGER,
	away_player_10	INTEGER,
	away_player_11	INTEGER,
	goal	TEXT,
	shoton	TEXT,
	shotoff	TEXT,
	foulcommit TEXT,
    "card" TEXT,
	"cross" TEXT,
	corner	TEXT,
	possession	TEXT,
	B365H	NUMERIC,
	B365D	NUMERIC,
	B365A	NUMERIC,
	BWH	NUMERIC,
	BWD	NUMERIC,
	BWA	NUMERIC,
	IWH	NUMERIC,
	IWD	NUMERIC,
	IWA	NUMERIC,
	LBH	NUMERIC,
	LBD	NUMERIC,
	LBA	NUMERIC,
	PSH	NUMERIC,
	PSD	NUMERIC,
	PSA	NUMERIC,
	WHH	NUMERIC,
	WHD	NUMERIC,
	WHA	NUMERIC,
	SJH	NUMERIC,
	SJD	NUMERIC,
	SJA	NUMERIC,
	VCH	NUMERIC,
	VCD	NUMERIC,
	VCA	NUMERIC,
	GBH	NUMERIC,
	GBD	NUMERIC,
	GBA	NUMERIC,
	BSH	NUMERIC,
	BSD	NUMERIC,
	BSA	NUMERIC
	-- FOREIGN KEY(country_id) REFERENCES country(id),
	-- FOREIGN KEY(league_id) REFERENCES League(id),
	-- FOREIGN KEY(home_team_api_id) REFERENCES Team(team_api_id),
	-- FOREIGN KEY(away_team_api_id) REFERENCES Team(team_api_id),
	-- FOREIGN KEY(home_player_1) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_2) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_3) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_4) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_5) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_6) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_7) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_8) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_9) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_10) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(home_player_11) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_1) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_2) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_3) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_4) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_5) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_6) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_7) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_8) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_9) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_10) REFERENCES Player(player_api_id),
	-- FOREIGN KEY(away_player_11) REFERENCES Player(player_api_id)
);

COPY Match FROM '/home/pratyush/Downloads/Project 1/Tables/Match.csv' DELIMITER ',' CSV HEADER;



-- DROP TABLE Match;