CREATE TABLE Player_Attributes (
	id	SERIAL PRIMARY KEY,
	player_fifa_api_id	INTEGER,
	player_api_id	INTEGER,
	date	TEXT,
	overall_rating	INTEGER,
	potential	INTEGER,
	preferred_foot	TEXT,
	attacking_work_rate	TEXT,
	defensive_work_rate	TEXT,
	crossing	INTEGER,
	finishing	INTEGER,
	heading_accuracy	INTEGER,
	short_passing	INTEGER,
	volleys	INTEGER,
	dribbling	INTEGER,
	curve	INTEGER,
	free_kick_accuracy	INTEGER,
	long_passing	INTEGER,
	ball_control	INTEGER,
	acceleration	INTEGER,
	sprint_speed	INTEGER,
	agility	INTEGER,
	reactions	INTEGER,
	balance	INTEGER,
	shot_power	INTEGER,
	jumping	INTEGER,
	stamina	INTEGER,
	strength	INTEGER,
	long_shots	INTEGER,
	aggression	INTEGER,
	interceptions	INTEGER,
	positioning	INTEGER,
	vision	INTEGER,
	penalties	INTEGER,
	marking	INTEGER,
	standing_tackle	INTEGER,
	sliding_tackle	INTEGER,
	gk_diving	INTEGER,
	gk_handling	INTEGER,
	gk_kicking	INTEGER,
	gk_positioning	INTEGER,
	gk_reflexes	INTEGER,
	-- FOREIGN KEY(player_fifa_api_id) REFERENCES Player(player_fifa_api_id), (Foreign key violations. Key (player_fifa_api_id)=(200529) is not present in table "player".)
	FOREIGN KEY(player_api_id) REFERENCES Player(player_api_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COPY Player_Attributes FROM '/home/pratyush/Downloads/Project 1/Tables/Player_Attributes.csv' DELIMITER ',' CSV HEADER;

-- DROP TABLE Player_Attributes;
